### Python Libraries for Data Science
-https://scipy.org/
### Numpy Library
- Processing N-Dimensional arrays

In [1]:
import numpy as np
li = [1,2,3]
a = np.array(li)
a


array([1, 2, 3])

In [2]:
import numpy as np
li = [1,2,3]
a = np.array(li)
type(a)


numpy.ndarray

In [3]:
import numpy as np
li = [1,2,3,'Z']
a = np.array(li)
a


array(['1', '2', '3', 'Z'], dtype='<U11')

In [4]:
import numpy as np
li = [1,2,3]
a = np.array(li)
b = np.arange(15)
b


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
import numpy as np
li = [1,2,3]
a = np.array(li)
b = np.arange(15)
a

array([1, 2, 3])

In [6]:
# Generating of  random numbers
import numpy as np
rn = np.random.randint(0,100,size=10)
rn


array([45,  8, 44, 79, 83, 13, 88, 71,  5, 63])

In [7]:
#Multi dimensional Arrays
import numpy as np
m3 = np.random.randint(0,1,size=(3,3))
m3


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
import numpy as np
m2 = np.random.randint(0,1,size=(2,2))
m2

array([[0, 0],
       [0, 0]])

In [9]:
# How to parse this datastructure
import numpy as np
m3 = np.random.randint(0,2,size=(3,3,3))
m3

array([[[1, 1, 1],
        [0, 1, 0],
        [1, 1, 0]],

       [[1, 1, 0],
        [1, 1, 0],
        [0, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [1, 1, 0]]])

In [11]:
import numpy as np
m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]

1

In [12]:
m3.ndim#number of dimensions


(3, 3, 3, 3)

In [13]:
m3.size


(3, 3, 3, 3)

In [14]:
m3.shape

(3, 3, 3, 3)

In [15]:
m3.dtype

dtype('int32')

In [16]:
m3.itemsize

4

In [17]:
m3.nbytes


324

In [19]:
m3[2,-1]#lastelement

array([[0, 0, 1],
       [0, 0, 0],
       [1, 1, 0]])

In [ ]:
x[:5]#first five elements
x[5:]#elements after index 5
x[4:7]
x2[:2,:3]#two rows ,three columns
x2[:3,::2]# all rows , every other column
x2[::-1,::-1] #can be reversed

In [20]:
print(b) # remove the commas

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [23]:
#Reshape 
b.reshape(5,3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
#Vectorized and UnVectorized
# Visualization

### Pandas (Library)=> Worked on Table Data
Use Cases
- Data Cleaning
- Data Transformation
- Data Analysis
Notations
- Series(One Dimensional)
- DataFrames(Two Dimesional)

In [26]:
import pandas as pd
internal1 = {'s1' : 22, 's2':18, 's3' :24}
internal1 = pd.Series(internal1)
internal1


s1    22
s2    18
s3    24
dtype: int64

In [27]:
#Two Dimensional
import pandas as pd
internal1 = {'s1' : 22, 's2':18, 's3' :24}
internal1 = pd.Series(internal1)
internal2 ={'s1':15,'s2':18,'s3':12}
internal2 = pd.Series(internal2)
internal2


s1    15
s2    18
s3    12
dtype: int64

In [28]:
final = {'internal1' : internal1,'internal2' : internal2}
final = pd.DataFrame(final)
final

internal1  internal2
s1         22         15
s2         18         18
s3         24         12

In [33]:
# DataFrame->Two dimentional represention of data and collection of rows and columns,Frame->One View of the data.
final = {'internal1' : internal1,'internal2' : internal2}
final = pd.DataFrame(final)
final["Internal1"]


KeyError: 'Internal1'

In [34]:
final.columns# Names of Columns

Index(['internal1', 'internal2'], dtype='object')

In [32]:
final.values# list of all rows

array([[22, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [35]:
final.values[2]

array([24, 12], dtype=int64)

In [37]:
final.values[2,0]
final.values[2][0]#both are correct

24

In [38]:
for row in final.values:
    print ('Internal-',row[0],',Internal2 -',row[1])

Internal- 22 ,Internal2 - 15
Internal- 18 ,Internal2 - 18
Internal- 24 ,Internal2 - 12


In [39]:
final


internal1  internal2
s1         22         15
s2         18         18
s3         24         12

In [40]:
final.loc[3]=[15,18]#loc is location
final

internal1  internal2
s1         22         15
s2         18         18
s3         24         12
3          15         18

In [41]:
final.loc['s4']=[16,12]#loc is location
final

internal1  internal2
s1         22         15
s2         18         18
s3         24         12
3          15         18
s4         16         12

In [42]:
final.drop(3)

internal1  internal2
s1         22         15
s2         18         18
s3         24         12
s4         16         12

In [43]:
final

internal1  internal2
s1         22         15
s2         18         18
s3         24         12
3          15         18
s4         16         12

In [45]:
final.values[2] = [12,25]
final

internal1  internal2
s1         22         15
s2         18         18
s3         12         25
3          15         18
s4         16         12

In [46]:
#Reading CSV file data
import pandas as pd
filepath = 'krishna/Income.csv'
incomedf = pd.read_csv(filepath)

incomedf 

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [47]:
# Extract income of all states in 2013
#california : 57528
incomedf.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 47215, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [48]:
# Extract income of all states in 2013
for row in incomedf.values:
    print(row[1],':',row[-1])
    

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [50]:
# Average Income of Arizona
sum = 0
for i in range(2,11):
    sum += incomedf.values[2][i]
sum/len(incomedf.values[2][2:])



47214.77777777778

In [3]:
# Average  income of all states in year  2012
 sum =0
for row in incomedf.values:
    sum += row[-2]
sum/len(incomedf.values)


IndentationError: unexpected indent (<ipython-input-3-e4d95de15afe>, line 2)

In [1]:
# Average  income of all states in year  2012
sum =0
for row in incomedf.values:
    sum += row[2:]
sum


NameError: name 'incomedf' is not defined

In [ ]:
colu